version: 2
executorType: docker
containerInfo:
  - image: underwaterpony/centos:20180307
    environment:
      MAVEN_OPTS: "-Xms1024m -Xmx2048m"
stages:
  build:
    workDir: /root/shazamcrest
    steps:
      - type: checkout

      - type: cache-restore
        keys:
          - maven-{{ checksum "pom.xml" }}

      - type: run
        name: "Maven (site, deploy)"
        command: mvn site deploy -s settings.xml --batch-mode --update-snapshots

      - type: cache-save
        key: maven-{{ checksum "pom.xml" }}
        paths:
          - "~/.m2"