version: 2
jobs:
  build:
    environment:
      - MAVEN_OPTS: "-Xms1024m -Xmx2048m"
    working_directory: ~/shazamcrest
    docker:
      - image: underwaterpony/centos:latest
    steps:
      - checkout
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run: command: mvn site deploy -s settings.xml --batch-mode --update-snapshots
      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - "~/.m2"
